### ISSUE TITLE
package.json not in a parent folder of eslint working directory

### ISSUE THREAD

**Issue by laurentgoudet** [nfl/jspm-resolve#3]
`jspm-resolve` uses `find-root` to get the `package.json` path. However, in our current weird setup, the `package.json` manifest & `node_modules` folder live in a directory which is not a parent of our code base (on which we run `eslint`), e.g. (simplified view):

- `static/`
- `static/js/`
- `static/js/.eslintrc`
- `static/js/somefile.js`
- `static/jspm_packages/`
- `support/`
- `support/build-assets/`
- `support/build-assets/package.json`
- `support/build-assets/node_modules/`

Is there a way we could make `eslint-import-resolver-jspm` work without changing that structure? Thanks!

**Comment by doctyper** [comment]
Hm. Would you be opposed to a symlink on the root of your project? e.g.

```
ln -s support/build-assets/package.json package.json
```

**Comment by doctyper** [comment]
@laurentgoudet Fix published in [`eslint-import-resolver-jspm@1.2.0`](https://www.npmjs.com/package/eslint-import-resolver-jspm). Usage:

```js
{
    "settings": {
        "import/resolver": {
            "jspm": {
                "rootDir": "./path/to/custom/jspmRootDir"
            }
        }
    }
}
```

**Comment by laurentgoudet** [comment]
Wow thanks! Is there a way for `rootDir` to be relative to `.eslintrc` though? It seems to be relative to `eslint` current working directory for now, which breaks text editors/IDEs eslint integrations. A symlink won't work for us as well with our remote dev environments setup :/.

**Comment by doctyper** [comment]
Perhaps. I think this is as far as I want to take this configuration, but please feel free to contribute if you land on a solution.
