### ISSUE TITLE
import/no-unresolved with SystemJS plugins

### ISSUE THREAD

**Issue by screendriver** [nfl/jspm-resolve#7]
I am using your [eslint-import-resolver-jspm](https://github.com/nfl/jspm-resolve/tree/master/plugins/eslint-import-resolver-jspm) but don't get it running with SystemJS plugins. For SystemJS plugins you have to add a `!` at the end of the import.

For example I am using [plugin-text](https://github.com/systemjs/plugin-text) and import a file like so

`import myText from './test-file.hml!text';`

Is there a way I can tell eslint-plugin-import to check that the file exists but don't parse the content? I played around with `"import/ignore"` and `import/no-unresolved: [2, { ignore: ['\.html$'] }]` but don't get it running 😕

If I set `ignore` in my rules the file will be completely ignored. That's what I want. But it doesn't check if the file exists. So I can write anything I want. If I only set `"import/ignore": ['.html$'],` it gives me an error because it can't find the file `test-file.html!text'` on the file system (it should only look for `test-file.html` and not for `test-file.html!text`)

**Comment by doctyper** [comment]
If I'm not mistaken this issue is more of a eslint-plugin-import issue. This resolver is more of a glue layer between it and jspm. Have you tried opening an issue there?

**Comment by screendriver** [comment]
Hmm you are right. Sorry, my bad.
